### ISSUE TITLE
TODO/FIXME Count 9

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/crypto-ld#50]
- [ ] FIXME: multicodec doesn't know about 0x5d encoding yet
       Commit: (091cca4) Add APIs and tests.
       File:  [tests/ld-key-pair.spec.js:324](https://github.com/digitalbazaar/crypto-ld/blob/master/tests/ld-key-pair.spec.js#L324)
       Matthew Collier commented a year ago

  - [ ] FIXME: https://github.com/digitalbazaar/crypto-ld/issues/43
       Commit: (f325df2) Skip failing test.
       File:  [tests/ld-key-pair.spec.js:318](https://github.com/digitalbazaar/crypto-ld/blob/master/tests/ld-key-pair.spec.js#L318)
       Matthew Collier commented 2 months ago

  - [ ] TODO: Add a brief discussion of where to store the private keys. Point to
       Commit: (892c595) Expand README, add Usage docs.
       File:  [README.md:71](https://github.com/digitalbazaar/crypto-ld/blob/master/README.md#L71)
       Dmitri Zagidulin commented 7 months ago

  - [x] TODO: Add design considerations for choosing key types / cryptographic
       Commit: (892c595) Expand README, add Usage docs.
       File:  [README.md:58](https://github.com/digitalbazaar/crypto-ld/blob/master/README.md#L58)
       Dmitri Zagidulin commented 7 months ago

**Comment by JSAssassin** [comment]
Closing. Generated new TODO/FIXMEs and there were none pending.
